# <center> LAB EXAM </center>

## Slicing

In [39]:
import numpy as np
A = np.mat(input("Enter the numbers: "))
#1,5,8,15,8;9,4,9,14,8;2,3,18,13,9;8,2,17,12,13;7,1,16,0,121
print(A)
print(A[2::2,[0,3,4]])
print(A[[0,2]])

Enter the numbers: 1,5,8,15,8;9,4,9,14,8;2,3,18,13,9;8,2,17,12,13;7,1,16,0,121
[[  1   5   8  15   8]
 [  9   4   9  14   8]
 [  2   3  18  13   9]
 [  8   2  17  12  13]
 [  7   1  16   0 121]]
[[  2  13   9]
 [  7   0 121]]
[[ 1  5  8 15  8]
 [ 2  3 18 13  9]]


# Eigen values

In [29]:
A = np.mat(input("Enter the values: "))
#1,2,3;4,5,1;6,2,1
print(A)
ev,evec = np.linalg.eig(A)
print("The eigen values are: {}".format(np.around(ev)))
print("The eigen vectors are: \n{}".format(np.around(evec)))
A = np.append(ev)

Enter the values: 1,2,3;4,5,1;6,2,1
[[1 2 3]
 [4 5 1]
 [6 2 1]]
The eigen values are: [ 8. -3.  2.]
The eigen vectors are: 
[[-0. -1.  0.]
 [-1.  0. -1.]
 [-1.  1.  1.]]


NameError: name 'append' is not defined